config/routes.rb
BlogApp::Application.routes.draw do
  get "sessions/new"
  get '/' => "posts#index"
  get '/index' => "posts#index"
  get '/show/:id' => "posts#show"
  get '/post/new' => "posts#new"
  post '/post/create' => "posts#create"
  delete '/post/delete/:id' => "posts#destroy", :as => 'destroy_post'
  get ':id/comments/new' => "comments#new"
  post ':id/comments/new' => "comments#create"
  delete '/comments/delete/:id' => "comments#delete", :as => 'destroy_comment'
  get '/signup' => "users#new"
  post '/signup' => "users#create"
  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  delete 'logout' => "sessions#destroy"

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :comments
	has_many :posts
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :logged_in_user
	
	def new
		@post = Post.find_by(id: params[:id])
		@comment = @current_user.comments.new
	end

	def create
		@post = Post.find_by(id: params[:id])
		@comment = @current_user.comments.create(comment_params)
		@comment.post_id = @post.id
		@comment.save
		redirect_to controller: "posts", action: "show", id: @post.id
	end

	def destroy
		@comment = Comment.find_by(id: params[:id])
		if @comment.present?
			@id = @comment.post_id
			@comment.delete
		end
		redirect_to controller: "posts", action: "show", id: @id
	end

	private

		def comment_params
			params.require(:comment).permit(:body)
		end

		def logged_in_user
			unless logged_in?
				flash[:danger] = "Please log in!"
				redirect_to '/login'
			end
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :logged_in_user 

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find_by(id: params[:id])
		@comments = @post.comments
	end

	def new
		@post = @current_user.posts.new
	end

	def create
		@post = @current_user.posts.new(post_params)
		if @post.save
			redirect_to '/index'
		end
	end

	def destroy
		@post = Post.find_by(id: params[:id])
		@post.comments.delete
		@post.delete
		redirect_to '/index'
	end


	private

		def post_params
			params.require(:post).permit(:title, :body)
		end

		def logged_in_user
			unless logged_in?
				flash[:danger] = "Please log in!"
				redirect_to '/login'
			end
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if logged_in?
        flash[:danger] = "Please log out first!"
        redirect_to '/index'
    end
  end

  def create
  	user = User.find_by(email: params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in(user)
  		redirect_to '/index'
  	else
  		flash[:danger] = "Email/password combination incorrect!"
  		redirect_to '/login'
  	end
  end

  def destroy 
  	log_out
  	redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :not_logged_in_user

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			log_in @user
			flash[:danger] = "Welcome " + @user.email
			redirect_to '/index'
		else
			flash[:danger] = "Signup failed! Make sure data is correctly entered!"
			redirect_to '/signup'
		end
	end

	private

		def not_logged_in_user
			if logged_in?
				flash[:danger] = "Please log out first!"
				redirect_to '/index'
			end
		end

		def user_params
			params.require(:user).permit(:email, :password, :password_confirmation)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user = @current_user || User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def not_logged_in?
		current_user.nil?
	end

	def log_out
		session.delete(:user_id)
		@current_user = nil
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= form_for(@comment, method: :post, :url => {contoller: "comments", action: "create", id: params[:id]}) do |f| %>
<%= f.label :comment_body %>
<br>
<br>
<%= f.text_area :body %>
<br>
<br>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |message_type, message| %>
<%= message %>
<br>
<br>
<% end %>
<% if logged_in? %>
<%= link_to "Home", '/index' %>
<% end %>
<br>
<br>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<div class="container-fluid">
	<nav class="navbar navbar-inverse"></nav>
</div>


<% if logged_in? %>
<%= link_to "Logout", '/logout', method: 'delete' %>
<% end %>
<br>
<br>
<div class="container">
	<div class="jumbotron" style="background-color:#00FFFF">
		<h1 style="text-align:center">Welcome to BlogApp</h1>
	</div>
<div style="height:30px; text-align:center"><h3>This is a list of all the posts in this blog:</h3></div>
<br>
<% @posts.each do |p| %>
<div style="text-align:center"><%= link_to p.title, controller:"posts", action:"show", id: p.id %></div>
<div style="height:15px"></div>
<% end %>
<!--<div style="height:30px">------------------------------</div>-->
<%= link_to "Write a post", {controller: "posts", action: "new"}, {class: "btn btn-success btn-lg btn-block"} %>
</div>

app/views/posts/new.html.erb
<h1><div style="height:40px; text-align:center">Write your post</div></h1>
<%= form_for(@post, method: :post, url: '/post/create') do |f| %>
<br>
<div style="text-align:center"><%= f.label :title %></div>
<div style="text-align:center"><%= f.text_field :title %></div>
<div style="height:15px"></div>
<div style="text-align:center"><%= f.label :body %></div>
<div style="text-align:center"><%= f.text_area :body %></div>
<br>
<br>
<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div style="height:30px;color:green">This is the detailed view of Post <%= @post.id %>:</div>
<div><label style="color:blue">Post title: </label><%= @post.title %></div>
<div style="height:10px"></div>
<div><label style="color:blue">Post body: </label><%= @post.body %></div>    
<div style="height:10px"></div>
<% if @post.user.present? %>
<% if @current_user.id == @post.user_id %>
<%= link_to 'Destroy', destroy_post_path, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>
<% end %>
<br>
<br>
<% @comments.each do |comment| %>
<% if comment.user.present? %>
<label style="color:red"><%= comment.user.email %>:</label>    
<% end %>
<% if !comment.user.present? %>
<label style="color:red">No user - </label>
<% end %>
<%= comment.body %>
<% if @current_user.id == comment.user_id %>
<%= link_to 'Destroy', destroy_comment_path, method: :delete %>
<% end %>
<div style="height:7px"></div>
<% end %>
<%= link_to "Add a comment", id: @post.id, controller: "comments", action: "new" %>

app/views/users/new.html.erb
<%= form_for(@user, method: :post, :url => {controller: "users", action: "create"}) do |f| %>
<%= f.label :email %>
<%= f.text_field :email %>
<br>
<br>
<%= f.label :password %> 
<%= f.password_field :password %>
<br>
<br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<br>
<br>
<%= f.submit %>
<% end %>